#!/bin/bash

#script for marking point in video to continue watching later, if no point is
#specified will start from beginning next time.

#add get_time_pos bind on input.conf on any key you want
#create folder .mplayer/continue

BASENAME=`basename "$1"`
SAVEFILE="$HOME/.mplayer/continue/$BASENAME"
if [[ -f $SAVEFILE ]];then
    LASTPOS=$(tail -n 1 "$SAVEFILE")
fi

if [[ -z $LASTPOS ]]; then
    LASTPOS=0
fi

if [[ -f "$1" ]];then
    /usr/bin/mplayer "$1" ${*:2} -ss $LASTPOS | \
        grep 'ANS_TIME_POSITION' | \
        cut -d"=" -f2 > "$SAVEFILE"
else
    /usr/bin/mplayer ${*:1}
fi

if [[ -f $SAVEFILE ]];then
    LASTPOS=$(tail -n 1 "$SAVEFILE")
    if [[ -z $LASTPOS ]]; then
        rm "$SAVEFILE" 
    fi
fi
