#!/bin/bash

#script for marking point in video to continue watching later, if no point is
#specified will start from beginning next time.

#add get_time_pos bind on input.conf on any key you want
#create folder .mplayer/continue
#FIXME simplify the script

BASENAME=`basename "$1"`
#if savefile exists, grab that last pos
SAVEFILE="$HOME/.mplayer/continue/$BASENAME"
if [[ -f $SAVEFILE ]];then
    LASTPOS=$(tail -n 1 "$SAVEFILE")
fi

#if there's no lastpos, set it to zero
if [[ -z $LASTPOS ]]; then
    LASTPOS=0
fi

#if first parameter is file prepare to save bookmark
#else pass all parameters to mplayer
if [[ -f "$1" ]];then
    /usr/bin/mplayer "$1" ${*:2} -ss $LASTPOS | \
        grep 'ANS_TIME_POSITION' | \
        cut -d"=" -f2 > "$SAVEFILE"
else
    /usr/bin/mplayer $*
fi

#if no bookmark is saved, remove the file
if [[ -f $SAVEFILE ]];then
    LASTPOS=$(tail -n 1 "$SAVEFILE")
    if [[ -z $LASTPOS ]]; then
        rm "$SAVEFILE" 
    fi
fi
